### ISSUE TITLE
CSV import validation

### ISSUE THREAD

**Issue by barnabywalker** [stevenpbachman/geocat_staging#1]
Add a suite of functions to validate an imported CSV and display informative error messages, covering:

* missing values
* non-numeric longs and lats
* missing longs and lats columns
* numbers out of range

These should link to the UI by displaying the error message(?s) in a box and not loading anything for analysis.

**Comment by barnabywalker** [comment]
Possibly want to allow missing coordinates but present a warning to the user.

**Comment by gistin** [comment]
# Code attached, but this kills the apps, so need to replace stop with something sensible and change ifs to "if else"

#user data
thefilename <- file.choose()
thefile <- read.csv(thefilename)
shllcheck(thefile)

#or some false data (around Madagascar)
lat <- runif (200,-24,-12)
long <- runif (200,43,51)
thepoints <- data.frame(lat,long)
llp[1:10,] <- c(10,10)
llp[11:100,] <- c(0,0)
shllcheck(llp)



######################################################################
#Crude dataframe check for sensible latitude and longitude data
######################################################################
#' @title 
#' Check point data and latitude and longitude are sensible to work with
#' @description 
#' Checked the dataframe for NA, latitude below -90 or above 90, longitude below -180 and above 180, also warns if it finds whole numbers or 0
#' @author Justin Moat. J.Moat@kew.org
#' @param thepoints set of points as a dataframe with latitude and longitude 
#' @return nothing or warning or error
#' @note
#' this used as a quick check to see if data can be worked with and are on the earth. 
#' If coordinate cleaning is required we suggest you review https://cran.r-project.org/web/packages/CoordinateCleaner/index.html
#' @examples 
#' # build dataframe
#' lat <- runif (200,-24,-12)
#' long <- runif (200,43,51)
#' llp <- data.frame(lat,long)
#' #add some odd data
#' llp[1:10,] <- c(10,10)
#' llp[11:100,] <- c(0,0)
#' #below will return two warnings
#' shllcheck(llp)
#' llp[101,]<- NA
#' #below will return an error
#' shllcheck(llp)
#' llp[101,]<- c(1000,-20)
#' #below will return an error
#' shllcheck(llp)
#' llp[101,]<- c(-20,1000)
#' #below will return an error
#' shllcheck(llp)

shllcheck <- function(thepoints){
  #field name check
  if(is.null(thepoints$lat) | is.null(thepoints$long)){
    stop("data should be in lat long ie with field names lat long")
    #could be forgiving and work with lat or long or caps etc and rename?
  }
  #data type check
  if(!(is.numeric(thepoints$lat) | is.numeric(thepoints$lat))){
    stop("Some of the latitudes or longitutes are not numbers")
  }
  #Check for NA's, could just warn and remove?
  if (lapply(thepoints,function(x) any(is.na(x)))$lat | lapply(thepoints,function(x) any(is.na(x)))$long ){
    stop("Empty (NA) latitudes or longtitudes within you data, please remove any NA")
  }
  #lat
  if(any(thepoints$lat < -90) | any(thepoints$lat > 90)){
    stop("-90 < lat > 90, latitude not within sensible limits")
  }
  #long
  if(any(thepoints$long < -180) | any(thepoints$long > 180)){
    stop("-180 < long > 180, longtitude not within sensible limits")
  }
  pwhole <- sum(round(thepoints) == thepoints)/(nrow(thepoints) * ncol(thepoints))
  if (pwhole > 0.1){
    warning(paste (pwhole*100, "% of your points are whole numbers, as you sure they are in lat long?"), call. = FALSE)
  }
  pzero <- sum(thepoints == 0)/(nrow(thepoints) * ncol(thepoints))
  if (pzero > 0){
    warning(paste (pzero*100, "% of your points have 0 lat or long, are these true lat longs or no data, if no data then remove?"), call. = FALSE)
  }
}
