### ISSUE TITLE
display AOO cells on map

### ISSUE THREAD

**Issue by stevenpbachman** [stevenpbachman/geocat_staging#20]
as per geocat - display when analysis button is switched on. 

Consider moving between lat long and projected.

**Comment by gistin** [comment]
Easiest is if we implement rCAT2 or at least duplication the code. We will need to have the following procedure.
1. user imports csv (or GBIF data)
2. csv is checked to be sensible (maybe skip for GBIF)
3. project data and add fields X, Y
4. make sure projection is recorded
5. Any changes to tables or moving of points we will need to update or add X,Y and recalculate shapes and areas

**Comment by gistin** [comment]
library (rCAT)
#dummy data
lat <- runif (10,-18.5,-18)
long <- runif (10,47,47.5)
ll <- data.frame(lat,long)
#Choose the centre point from your set of points
pointsprojected <- simProjWiz(ll)

#EOO poly
epoly <- eoo (pointsprojected,TRUE)
#AOO
apolys <- aoo(pointsprojected,cellsize = 5000,returnV = "SF")

#reproject shapes back to to ll
epolyll <- st_transform(epoly,crs = 4326)
apolysll <- st_transform(apolys,crs = 4326)
#build labels
eoolab <- paste("EOO area", round(eoo(pointsprojected),2),"KM2")
aoolab <- paste("AOO area", round(aoo(pointsprojected),0),"KM2")

#add to map
m <- addPolygons(m,data = epolyll,weight = 1,color = 'red',label=eoolab)
m <- addPolygons (m,data = apolysll,weight = 1,color = 'green',label=aoolab)
m

**Comment by gistin** [comment]
New code for on the fly transformations. Presently a bit slow, but will do for the moment. Functions at the bottom and needs rcat2

**Comment by gistin** [comment]
library (leaflet)
m <- leaflet()
m <- addTiles(m)

############
library (rCAT)

#dummy data
lat <- runif (1000,-18.5,-18)
long <- runif (1000,47,47.5)
ll <- data.frame(lat,long)
#should have initial csv check here

#default AOOcellsize (maybe from slider if needed or wanted)
dcellsize = 2000

#get eoo
eoor <- eooll (ll)

#get aoo
aoor <- aooll(ll,cellsize = dcellsize)
end_time <- Sys.time()

#build the maps

#build labels
eoolab <- paste("EOO area", round(eoor$area/1000000,2),"KM2")
aoolab <- paste("AOO area", round(aoor$area/1000000,0),"KM2")

#add to map
m <- addPolygons(m,data = eoor$poly,weight = 1,color = 'red',label=eoolab)
m <- addPolygons (m,data = aoor$poly,weight = 1,color = 'green',label=aoolab)
m
#report projection used for calculations, needs to be reported somewhere?
paste("Projection used:", eoor$proj$input)


#######################################################
#functions
#######################################################
#EOO from Lat Long
#Returns list of polygons, area and projection used
eooll <- function(thepoints){
  #1 project
  ppoints<- simProjWiz(thepoints)
  #2 get poly
  ppoly <- eoo(ppoints, returnV = "SF")
  #3 reproject to ll
  llpoly <- st_transform(ppoly,crs = 4326)
  #return polygon and projection user
  return (list(poly=llpoly,area=st_area(ppoly), proj=st_crs(ppoly)))
}

#AOO from list of polygons
#Returns list of polygons, area and projection used
aooll <- function(thepoints,cellsize){
  #1 project
  ppoints<- simProjWiz(thepoints)
  #2 get poly
  ppoly <- aoo(ppoints, returnV = "SF",cellsize = cellsize)
  #3 reproject to ll
  llpoly <- st_transform(ppoly,crs = 4326)
  #return polygon and projection user
  return (list(poly=llpoly,area=sum(st_area(ppoly)),proj=st_crs(ppoly)))
}

**Comment by gistin** [comment]
Solved in my branch. Close when merged

**Comment by stevenpbachman** [comment]
closed with #30
